title: CLAP BAR - Escáner QR
description: Aplicación web con escáner de códigos QR para dispositivos móviles
theme: minima
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

# Configuración para GitHub Pages
baseurl: ""
url: ""

# Excluir archivos innecesarios
exclude:
  - README.md
  - .gitignore
  - .github/

# Configuración de navegación
navigation:
  - title: Inicio
    url: /
  - title: Escáner QR
    url: /qr.html
